routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('foo', function () {
    return 'Hello World';
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/company', 'CompanyController');

Route::resource('/category', 'CategoryController');

Route::resource('/employee', 'EmployeeController');

Route::resource('/product', 'ProductController');

Route::post('/company/addProfile', 'CompanyController@addProfile');

Route::post('/company/deleteImage', 'CompanyController@deleteImage');

Route::post('/product/addProfile', 'ProductController@addProfile');

Route::post('/product/deleteImage', 'ProductController@deleteImage');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    protected $fillable = [
        'name', 'image', 'price', 'short_description', 'subcategory_id'
    ];

    public function subCategory()
    {
        return $this->belongsTo(Category::class, 'subcategory_id');
    }

    public function productImages()
    {
        return $this->hasMany(ProductImage::class, 'product_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\CompanyImage;
use App\Http\Requests\Request;
use App\Product;
use App\Http\Requests\ProductsRequest;
use App\ProductImage;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ProductsList = Product::paginate(10);
        return view('product.index', compact('ProductsList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $SubCategories = Category::whereNotNull('parent_id')->pluck('id', 'name');
        return view('product.create', compact('SubCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductsRequest $request)
    {

        $Number = random_int(1000000, 9000000000);
        $Name = $request->get('name');
        $ImageFiles = $request->file('image');
        $ImageName = $Number . $ImageFiles[0]->getClientOriginalName();
        $Price = $request->get('price');
        $Description = $request->get('short_description');
        $SubCategoryId = $request->get('subcategory_id');

        $Product = Product::create([
            'name' => $Name,
            'image' => '0',
            'price' => $Price,
            'short_description' => $Description,
            'subcategory_id' => $SubCategoryId
        ]);

        if($request->file('image')) {
            $Product->image = $ImageName;
            $Product->save();
            foreach ($ImageFiles as $Image){
                Storage::disk('local')->putFileAs('public/', $Image, $Number . $Image->getClientOriginalName());
                ProductImage::create([
                    'product_id' => $Product->id,
                    'image_name' => $Number . $Image->getClientOriginalName()
                ]);
            }
        }

        return redirect(route('product.index'));


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Product = Product::find($id);
        $SubCategories = Category::whereNotNull('parent_id')->pluck('id', 'name');
        $ProductImages = $Product->productImages;
        return view('product.update', compact('Product', 'SubCategories', 'ProductImages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

            $Product = Product::find($id);
            $Product->name = $request->get('name');
            $Product->price = $request->get('price');
            $Product->short_description = $request->get('short_description');
            $Product->subcategory_id = $request->get('subcategory_id');


            if($request->file('image') !== null) {
                $Number = random_int(1000000, 9000000000);
                $ImageFiles = $request->file('image');
                foreach ($ImageFiles as $Image) {
                    Storage::disk('local')->putFileAs('public/', $Image, $Number . $Image->getClientOriginalName());
                    ProductImage::create([
                        'product_id' => $Product->id,
                        'image_name' => $Number . $Image->getClientOriginalName()
                    ]);
                }
            }

            $Product->save();

        return redirect(route('product.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Product = Product::find($id);
        $Product->productImages()->delete();
        $Product->delete();
        return redirect(route('product.index'));
    }

    public function addProfile(Request $request)
    {

        if($request->get('imgID')) {
            $ProductImage = ProductImage::find($request->get('imgID'));
            $Product = $ProductImage->products;
            $Product->image = $ProductImage->image_name;
            $Product->save();
            return $ProductImage->image_name;
        }
    }

    public function deleteImage(Request $request)
    {

        if($request->get('imgID')) {
            $ProductImage = ProductImage::find($request->get('imgID'));
            Storage::disk('local')->delete('public/'. $ProductImage->image_name);
            $ProductImage->delete();
            $Product = $ProductImage->products;
            $Product->image = 0;
            $Product->save();
            return $request->get('imgID');
        }

    }
}

resources/views/product/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<style>
    .message_div{
        margin: 100px auto;
    }

    .create_cat_text{
        font-size: 45px;
        color: red;
    }
</style>

@if($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
                <ul>
                    @foreach($errors->all() as $error)
                        <li style="color: red;">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if($SubCategories->isEmpty())
                <div class="message_div text-center">
                    <p class="create_cat_text">
                        Please create SUBCATEGORY before creating product
                    </p>
                    <a class="btn btn-danger" href="{{route('category.create')}}">Create SubCategory</a>
                </div>
            @else
            <form action="{{route('product.store')}}" enctype="multipart/form-data" method="post">
                @csrf
                {{ method_field('POST') }}
                <div class="form_group">
                    <input type="text" placeholder="Product Name" class="form-control" name="name">
                    <input type="file" name="image[]" multiple="multiple">
                    <input type="text" placeholder="Product Price" class="form-control" name="price">
                    <input type="text" placeholder="Product Description" class="form-control" name="short_description">
                    <label for="category_select">Check SubCategory</label>
                    <select name="subcategory_id" id="category_select" class="form-control">
                        <option></option>
                        @foreach($SubCategories as $SubCategoryName => $SubCategoryId)
                            <option value="{{$SubCategoryId}}">{{$SubCategoryName}}</option>
                        @endforeach
                    </select>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </form>
            @endif
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/product/index.blade.php
<?php

use Illuminate\Support\Facades\Storage;


?>
        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <style>
        .my_tr  td, .my_tr  th{
            line-height: 100px;
        }

        .table tr td img{
            width: 100px;
            height: 100px;
        }

        .pagination{
            justify-content: center;
        }

        .nav-item a{
            text-decoration: none;
            color: #000;
            font-size: 35px;
        }

        .nav-item{
            border-right: 1px solid #818182;
        }

        .nav_left{
            background-color: #000000;
        }


        .nav_left a{
            color: #ffffff;
        }

        .modal-body h3{
            margin-bottom: 20px;
        }
    </style>
</head>
<body>


<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body text-center">
                <h5>Are you sure do you want to delete?</h5>
                <form style="display: inline-block;" class="delete_form" action="" method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    {{ csrf_field() }}
                    <button  type="submit" class="btn btn-success"  data-toggle="modal" data-target="#myModal">YES</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">NO</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>


<ul class="nav nav-tabs nav-justified md-tabs indigo" id="myTabJust" role="tablist">
    <li class="nav-item">
        <a href="/company">
            Companies
        </a>
    </li>
    <li class="nav-item">
        <a href="/employee">
            Employees
        </a>
    </li>
    <li class="nav-item">
        <a href="/category">
            Categories
        </a>
    </li>
    <li class="nav-item nav_left">
        <a href="/product">
            Products
        </a>
    </li>
</ul>
<div class="tab-content card pt-5" id="myTabContentJust">
    <div class="tab-pane fade show active" id="home-just" role="tabpanel" aria-labelledby="home-tab-just">
        <div class="crud_buttons">
            <a href="product/create" class="btn btn-success">Create</a>
        </div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Image</th>
                <th scope="col">Price</th>
                <th scope="col">Description</th>
                <th scope="col">SubCategory Id</th>
                <th scope="col">Created At</th>
                <th scope="col">Updated At</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @if($ProductsList)
                @foreach($ProductsList as  $Product)
                    <tr class="my_tr">
                        <th scope="row">{{$Product->id}}</th>
                        <td>{{$Product->name}}</td>
                        <td>
                            @if($Product->image === "0")
                                <img src="https://cdn.shopify.com/s/files/1/1486/9104/t/28/assets/no-img.jpg?0" alt="">
                            @else
                                <img src="{{'storage/' . $Product->image}}" alt="">
                            @endif
                        </td>
                        <td>{{$Product->price}} $</td>
                        <td>{{$Product->short_description}}</td>
                        <td>{{$Product->subcategory_id}}</td>
                        <td>{{$Product->created_at}}</td>
                        <td>{{$Product->updated_at}}</td>
                        <td>
                            <form style="display: inline-block;" action="{{route('product.destroy', $Product->id)}}" method="POST">
                                <input name="_method" type="hidden" value="DELETE">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-success del_modal"  data-toggle="modal" data-target="#myModal">X</button>
                            </form>
                            <a href="/product/{{$Product->id}}/edit" class="btn btn-success"><i class="far fa-edit"></i></a>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text_center">
                        {{ $ProductsList->links() }}
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>
    <div class="tab-pane fade" id="profile-just" role="tabpanel" aria-labelledby="profile-tab-just">

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
    $('.del_modal').on('click', function (e) {
        e.preventDefault();
        var form = $(this).parent();
        var form_action = form.attr('action');
        $('.delete_form').attr('action', form_action);
    })
</script>
</body>
</html>

resources/views/product/update.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Document</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .images_box {
            width: 100px;
            height: 100px;
            overflow: hidden;
            margin-right: 15px;
            position: relative;
        }

        .images_box img {
            width: 100%;
            height: 100%;

        }

        .images_block {
            margin-top: 50px;
            display: flex;
            flex-wrap: wrap;
            padding: 30px;
            border: 1px solid #000000;
        }


        .images_box a{
            padding: 5px;
            background-color: rgba(0,0,0,.4);
            position: absolute;
            right: 0;
            top: 0;
            color: #ffffff;
        }

        .modal-body form {
            display: inline-block;
        }
    </style>


</head>
<body>

<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
                <form action="">
                    @csrf
                    {{ method_field('POST') }}
                    <input type="hidden">
                    <button class="btn btn-success" id="delete_img">Delete</button>
                </form>

                <form action="" method="post">
                    @csrf
                    {{ method_field('POST') }}
                    <input type="hidden" name="logo">
                    <button class="btn btn-danger" id="add_img">Add Profile Photo</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
@if($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
                <ul>
                    @foreach($errors->all() as $error)
                        <li style="color: red;">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="images_box prof_img">
                @if($Product->image === '0')
                    <img src="https://cdn.shopify.com/s/files/1/1486/9104/t/28/assets/no-img.jpg?0" alt="">
                @else
                    <img src="../../storage/{{$Product->image}}" alt="">
                @endif
            </div>
        </div>
        <div class="col-md-10">
            <form action="{{route('product.update', $Product->id)}}" enctype="multipart/form-data" method="post">
                @csrf
                {{ method_field('PUT') }}
                <div class="form_group">
                    <input type="text" placeholder="Product Name" class="form-control" name="name" value="{{$Product->name}}">
                    <input type="file" name="image[]" multiple="multiple">
                    <input type="text" placeholder="Product Price" class="form-control" name="price" value="{{$Product->price}}">
                    <input type="text" placeholder="Product Description" class="form-control" name="short_description" value="{{$Product->short_description}}">
                    <label for="category_select">Check SubCategory</label>
                    <select name="subcategory_id" id="category_select" class="form-control">
                        <option></option>
                        @foreach($SubCategories as $SubCategoryName => $SubCategoryId)
                            <option @if ($Product->subcategory_id == $SubCategoryId) selected @endif   value="{{$SubCategoryId}}">{{$SubCategoryName}}</option>
                        @endforeach
                    </select>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
    @if($ProductImages)
    <div class="images_block">
            @foreach($ProductImages as $ProductImage)
                <div class="images_box" data-ImgID="{{$ProductImage->id}}">
                    <a href="" class="img_val" data-ImgID="{{$ProductImage->id}}"  data-toggle="modal" data-target="#myModal">
                        <i class="far fa-edit"></i>
                    </a>
                    <img src="../../storage/{{$ProductImage->image_name}}" alt="">
                </div>
            @endforeach
    </div>
    @endif
</div>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
    $('.img_val').on('click', function () {

        var val = $(this).data('imgid');
        $('.modal-body form input').val(val);

    })
</script>

<script>
    $(document).ready(function(e){
        $('#add_img').click(function(){
            $imgID = $('.modal-body form input').val();

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            jQuery.ajax({
                url: '/product/addProfile',
                type: 'post',
                data:{
                    'imgID':$imgID
                },
                success:function(data){
                    if (data){
                        $('.prof_img img').attr('src', '../../storage/'+ data )
                        $('body').removeClass("modal-open")
                        $('.modal-backdrop').removeClass('modal-backdrop');
                        $('#myModal').removeClass('show').css('display', 'none');
                    }
                    console.log(data);
                },
                error: function (xhr, b, c) {
                    console.log('error AddProfileImage');
                }
            });
            return false;
        });



        $('#delete_img').click(function(){

            $imgID = $('.modal-body form input').val();

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            jQuery.ajax({
                url: '/product/deleteImage',
                type: 'post',
                data:{
                    'imgID':$imgID
                },
                success:function(data){
                    if (data){
                        console.log(data);
                        $('.images_box').each(function () {
                            if( parseInt(data)  === $(this).data('imgid')){
                                $(this).remove();
                            }
                        })
                        $('body').removeClass("modal-open")
                        $('.modal-backdrop').removeClass('modal-backdrop');
                        $('#myModal').removeClass('show').css('display', 'none');
                    }
                },
                error: function () {
                    console.log('error DeleteImage');
                }
            });
            return false;
        });
    });
</script>

</body>
</html>