routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('foo', function () {
    return 'Hello World';
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/company', 'CompanyController');

Route::resource('/category', 'CategoryController');

Route::resource('/employee', 'EmployeeController');

Route::resource('/product', 'ProductController');

Route::post('/company/addProfile', 'CompanyController@addProfile');

Route::post('/company/deleteImage', 'CompanyController@deleteImage');

Route::post('/product/addProfile', 'ProductController@addProfile');

Route::post('/product/deleteImage', 'ProductController@deleteImage');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $timestamps = true;
    protected $table = 'categories';
    protected $fillable = [
        'name', 'parent_id'
    ];

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }


    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function products()
    {
        return $this->hasMany(Product::class, 'subcategory_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $CategoriesList = Category::paginate(10);
        return view('category.index', compact('CategoriesList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ParentCategories = Category::where('parent_id', null)->pluck('id', 'name');
        return view('category.create', compact('ParentCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {

        if($request) {
            Category::create($request->all());
        }
        return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Category = Category::find($id);
        $ParentCategories = Category::where('parent_id', null)->pluck('id', 'name');
        return view('category.update', compact('Category', 'ParentCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        Category::find($id)->update($request->all());
        return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ParentCategory = Category::find($id);
        $SubCategories = $ParentCategory->children()->delete();
        $Products = $ParentCategory->products()->delete();
        $ParentCategory->delete();
        return redirect(route('category.index'));
    }
}

resources/views/category/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

@if($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
                <ul>
                    @foreach($errors->all() as $error)
                        <li style="color: red;">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-2">
            <form action="{{route('category.store')}}" enctype="multipart/form-data" method="post">
                @csrf
                @method('POST')
                <div class="form_group">
                    <input type="text" placeholder="Name" class="form-control" name="name">
                    <label for="category_select">Check Parent Category</label>
                    <select name="parent_id" id="category_select" class="form-control">
                        <option></option>
                        @foreach($ParentCategories as $CategoryName => $CategoryId)
                            <option value="{{$CategoryId}}">{{$CategoryName}}</option>
                        @endforeach
                    </select>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/category/index.blade.php
<?php

use Illuminate\Support\Facades\Storage;


?>
        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <style>
        .my_tr  td, .my_tr  th{
            line-height: 100px;
        }

        .table tr td img{
            width: 100px;
            height: 100px;
        }

        .pagination{
            justify-content: center;
        }

        .nav-item a{
            text-decoration: none;
            color: #000;
            font-size: 35px;
        }

        .nav-item{
            border-right: 1px solid #818182;
        }

        .nav_left{
            background-color: #000000;
        }


        .nav_left a{
            color: #ffffff;
        }

        .modal-body h3{
            margin-bottom: 20px;
        }
    </style>
</head>
<body>


<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body text-center">
                <h5>Are you sure do you want to delete?</h5>
                <form style="display: inline-block;" class="delete_form" action="" method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    {{ csrf_field() }}
                    <button  type="submit" class="btn btn-success"  data-toggle="modal" data-target="#myModal">YES</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">NO</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>


<ul class="nav nav-tabs nav-justified md-tabs indigo" id="myTabJust" role="tablist">
    <li class="nav-item">
        <a href="/company">
            Companies
        </a>
    </li>
    <li class="nav-item">
        <a href="/employee">
            Employees
        </a>
    </li>
    <li class="nav-item nav_left">
        <a href="/category">
            Categories
        </a>
    </li>
    <li class="nav-item">
        <a href="/product">
            Products
        </a>
    </li>
</ul>
<div class="tab-content card pt-5" id="myTabContentJust">
    <div class="tab-pane fade show active" id="home-just" role="tabpanel" aria-labelledby="home-tab-just">
        <div class="crud_buttons">
            <a href="category/create" class="btn btn-success">Create</a>
        </div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Parent Id</th>
                <th scope="col">Created At</th>
                <th scope="col">Updated At</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @if($CategoriesList)
                @foreach($CategoriesList as  $Category)
                    <tr class="my_tr">
                        <th scope="row">{{$Category->id}}</th>
                        <td>{{$Category->name}}</td>
                        <td>
                            @if($Category->parent_id)
                                {{$Category->parent_id}}
                            @else
                                Null
                            @endif
                        </td>
                        <td>{{$Category->created_at}}</td>
                        <td>{{$Category->updated_at}}</td>
                        <td>
                            <form style="display: inline-block;" action="{{route('category.destroy', $Category->id)}}" method="POST">
                                <input name="_method" type="hidden" value="DELETE">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-success del_modal"  data-toggle="modal" data-target="#myModal">X</button>
                            </form>
                            <a href="/category/{{$Category->id}}/edit" class="btn btn-success"><i class="far fa-edit"></i></a>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text_center">
                        {{ $CategoriesList->links() }}
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>
    <div class="tab-pane fade" id="profile-just" role="tabpanel" aria-labelledby="profile-tab-just">

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
    $('.del_modal').on('click', function (e) {
        e.preventDefault();
        var form = $(this).parent();
        var form_action = form.attr('action');
        $('.delete_form').attr('action', form_action);
    })
</script>
</body>
</html>

resources/views/category/update.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

@if($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
                <ul>
                    @foreach($errors->all() as $error)
                        <li style="color: red;">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-2">
            <form action="{{route('category.update', $Category->id)}}" method="post">
                @csrf
                {{ method_field('PUT') }}
                <div class="form_group">
                    <input type="text" placeholder="Name" class="form-control" name="name" value="{{$Category->name}}">
                    <label for="category_select">Set or Update Parent Category</label>
                    <select name="parent_id" id="category_select" class="form-control" >
                        <option></option>
                        @foreach($ParentCategories as $CategoryName => $CategoryId)
                            <option @if ($Category->parent_id == $CategoryId) selected @endif   value="{{$CategoryId}}">{{$CategoryName}}</option>
                        @endforeach
                    </select>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>