routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('foo', function () {
    return 'Hello World';
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/company', 'CompanyController');

Route::resource('/category', 'CategoryController');

Route::resource('/employee', 'EmployeeController');

Route::resource('/product', 'ProductController');

Route::post('/company/addProfile', 'CompanyController@addProfile');

Route::post('/company/deleteImage', 'CompanyController@deleteImage');

Route::post('/product/addProfile', 'ProductController@addProfile');

Route::post('/product/deleteImage', 'ProductController@deleteImage');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    public $timestamps = true;


    protected $fillable = [
        'first_name', 'last_name', 'company_id', 'email', 'phone'
    ];

    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Employee;
use Illuminate\Http\Request;
use App\Http\Requests\EpmloyeeRequest;
class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees =  Employee::paginate(10);

        return view('employee.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies =  Company::pluck('id', 'name');

        return view('employee.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EpmloyeeRequest $request)
    {

        Employee::create($request->all());

        return redirect(route('employee.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee =  Employee::find($id);

        $companies = Company::pluck('id' , 'name');
        return view('employee.update', compact(['companies', 'employee']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EpmloyeeRequest $request, $id)
    {
        $company = Employee::find($id);

        optional($company)->update($request->all());

        return redirect(route('employee.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Employee $employee
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        return redirect(route('employee.index'));
    }
}

resources/views/employee/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

@if($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
                <ul>
                    @foreach($errors->all() as $error)
                        <li style="color: red;">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-2">
            <form action="{{route('employee.store')}}" enctype="multipart/form-data" method="post">
                @csrf
                @method('POST')
                <div class="form_group">
                    <input type="text" placeholder="First Name" class="form-control" name="first_name">
                    <input type="text" placeholder="Last Name" class="form-control" name="last_name">
                    <select name="company_id" id="" class="form-control">
                        <option value="">Check Company</option>
                        @foreach($companies as $company => $value)
                            <option value="{{$value}}">{{$company}}</option>
                        @endforeach
                    </select>
                    <input type="email" name="email" placeholder="Email" class="form-control">
                    <input type="text" name="phone" placeholder="+37477000000" class="form-control">
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/employee/index.blade.php
<?php

use Illuminate\Support\Facades\Storage;
?>
        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <style>
        .my_tr  td, .my_tr  th{
            line-height: 100px;
        }

        .table tr td img{
            width: 100px;
            height: 100px;
        }

        .pagination{
            justify-content: center;
        }

        .nav-item a{
            text-decoration: none;
            color: #000;
            font-size: 35px;
        }

        .nav-item{
            border-right: 1px solid #1b1e21;
        }

        .nav_right{
            background-color: #000000;
        }


        .nav_right a{
            color: #ffffff;
        }

        .modal-body h3{
            margin-bottom: 20px;
        }
    </style>
</head>
<body>

<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body text-center">
                <h5>Are you sure do you want to delete?</h5>
                <form style="display: inline-block;" class="delete_form" action="" method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    {{ csrf_field() }}
                    <button  type="submit" class="btn btn-success"  data-toggle="modal" data-target="#myModal">YES</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">NO</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<ul class="nav nav-tabs nav-justified md-tabs indigo" id="myTabJust" role="tablist">
    <li class="nav-item">
        <a href="/company" >
            Companies
        </a>
    </li>
    <li class="nav-item nav_right">
        <a  href="/employee" >
            Employees
        </a>
    </li>
    <li class="nav-item">
        <a href="/category">
            Categories
        </a>
    </li>
    <li class="nav-item">
        <a href="/product">
            Products
        </a>
    </li>
</ul>
<div class="tab-content card pt-5" id="myTabContentJust">
    <div class="tab-pane fade show active" id="home-just" role="tabpanel" aria-labelledby="home-tab-just">
        <div class="crud_buttons">
            <a href="employee/create" class="btn btn-success">Create</a>
        </div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Company Id</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($employees as  $employee)
                <tr class="my_tr">
                    <th scope="row">{{$employee->id}}</th>
                    <td>{{$employee->first_name}}</td>
                    <td>{{$employee->last_name}}</td>
                    <td>{{$employee->company_id}}</td>
                    <td>{{$employee->email}}</td>
                    <td>{{$employee->phone}}</td>
                    <td>
                        <form style="display: inline-block;" action="{{route('employee.destroy', $employee->id)}}" method="POST">
                            <input name="_method" type="hidden" value="DELETE">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-success del_modal"  data-toggle="modal" data-target="#myModal">X</button>
                        </form>
                        <a href="/employee/{{$employee->id}}/edit" class="btn btn-success"><i class="far fa-edit"></i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text_center">
                        {{ $employees->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="profile-just" role="tabpanel" aria-labelledby="profile-tab-just">

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
    $('.del_modal').on('click', function (e) {
        e.preventDefault();
        var form = $(this).parent();
        var form_action = form.attr('action');
        $('.delete_form').attr('action', form_action);
    })
</script>

</body>
</html>

resources/views/employee/update.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

@if($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
                <ul>
                    @foreach($errors->all() as $error)
                        <li style="color: red;">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-2">
            <form action="{{route('employee.update', $employee->id)}}" method="post">
                @csrf
                {{ method_field('PUT') }}
                <div class="form_group">
                    <input type="text" placeholder="First Name" class="form-control" name="first_name" value="{{$employee->first_name}}">
                    <input type="text" placeholder="Last Name" class="form-control" name="last_name" value="{{$employee->last_name}}">
                    <select name="company_id" id="" class="form-control" >
                        @foreach($companies as $company => $value)
                            <option @if ($employee->id == $value) selected @endif   value="{{$value}}">{{$company}}</option>
                        @endforeach
                    </select>
                    <input type="email" name="email" placeholder="Email" class="form-control" value="{{$employee->email}}">
                    <input type="text" name="phone" placeholder="+37477000000" class="form-control" value="{{$employee->phone}}">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>