routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('foo', function () {
    return 'Hello World';
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/company', 'CompanyController');

Route::resource('/category', 'CategoryController');

Route::resource('/employee', 'EmployeeController');

Route::resource('/product', 'ProductController');

Route::post('/company/addProfile', 'CompanyController@addProfile');

Route::post('/company/deleteImage', 'CompanyController@deleteImage');

Route::post('/product/addProfile', 'ProductController@addProfile');

Route::post('/product/deleteImage', 'ProductController@deleteImage');

app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Http\Requests\validRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
class CrudController extends Controller
{
    public function index()
    {
        $companies = Company::paginate(10);
        return view('crud.index', ['companies' => $companies]);
    }

    public function create(){
        return view('crud.create');
    }


    public function add(validRequest $request){
        $number = mt_rand(1000000000, 9999999999);
        $name = $request->get('name');
        $email = $request->get('email');
        $website = $request->get('website');
        $logo = $number . $request->file('logo')->getClientOriginalName();

        Company::create([
            'name'=> $name,
            'email'=> $email,
            'website' => $website,
            'logo'=> $logo
        ]);

        Storage::disk('local')->putFileAs('public/',$request->file('logo'), $logo);
        return redirect()->route('crud');
    }

    public function delete($id){
        $company =  Company::find($id);
        Storage::disk('local')->delete('public/'. $company->logo);
        $company->delete();
        return redirect()->route('crud');
    }

    public function update($id)
    {
        $company = Company::find($id);
        return view('crud.update', ['company' => $company]);
    }

    public function up(validRequest $request, $id){
        $number = mt_rand(1000000000, 9999999999);
        if($request->file('logo') !== null){
            $company =  Company::find($id);
            Storage::disk('local')->delete('public/'. $company->logo);
            $logo = $number . $request->file('logo')->getClientOriginalName();
            Storage::disk('local')->putFileAs('public/', $request->file('logo'), $logo);

            DB::table('companies')
                ->where('id', $id)
                ->update([

                    'name' => $request->get('name'),
                    'email' => $request->get('email'),
                    'logo' => $logo,
                    'website' => $request->get('website'),
                ]);
        } else{
            DB::table('companies')
                ->where('id', $id)
                ->update([

                    'name' => $request->get('name'),
                    'email' => $request->get('email'),
                    'website' => $request->get('website'),
                ]);
        }
        return redirect(route('crud'));
    }
}

resources/views/crud/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

    @if($errors->any())
        <div class="container">
            <div class="row">
                <div class="col-md-10 offset-2">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li style="color: red;">{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    @endif
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
               <form action="{{route('company.store')}}" enctype="multipart/form-data" method="post">
                   @csrf
                   {{ method_field('POST') }}
                    <div class="form_group">
                        <input type="text" placeholder="Name" class="form-control" name="name">
                        <input type="email" placeholder="Email" class="form-control" name="email">
                        <input type="text" placeholder="Website" class="form-control" name="website">
                        <input type="file" name="logo[]" multiple="multiple">
                        <button type="submit" class="btn btn-success">Create</button>
                    </div>
               </form>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/crud/index.blade.php
<?php

use Illuminate\Support\Facades\Storage;


?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <style>
        .my_tr  td, .my_tr  th{
            line-height: 100px;
        }

        .table tr td img{
            width: 100px;
            height: 100px;
        }

        .pagination{
            justify-content: center;
        }

        .nav-item a{
            text-decoration: none;
            color: #000;
            font-size: 35px;
        }

        .nav-item{
            border-right: 1px solid #818182;
        }

        .nav_left{
            background-color: #000000;
        }


        .nav_left a{
            color: #ffffff;
        }

        .modal-body h3{
            margin-bottom: 20px;
        }
    </style>
</head>
<body>


<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body text-center">
                <h5>Are you sure do you want to delete?</h5>
                <form style="display: inline-block;" class="delete_form" action="" method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    {{ csrf_field() }}
                    <button  type="submit" class="btn btn-success"  data-toggle="modal" data-target="#myModal">YES</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">NO</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>


<ul class="nav nav-tabs nav-justified md-tabs indigo" id="myTabJust" role="tablist">
        <li class="nav-item nav_left">
            <a href="/company">
                    Companies
            </a>
        </li>
        <li class="nav-item">
            <a href="/employee">
                Employees
            </a>
        </li>
        <li class="nav-item">
            <a href="/category">
                Categories
            </a>
        </li>
        <li class="nav-item">
            <a href="/product">
                Products
            </a>
        </li>
    </ul>
    <div class="tab-content card pt-5" id="myTabContentJust">
        <div class="tab-pane fade show active" id="home-just" role="tabpanel" aria-labelledby="home-tab-just">
            <div class="crud_buttons">
                <a href="company/create" class="btn btn-success">Create</a>
            </div>
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">logo</th>
                    <th scope="col">Website</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($companies as  $company)
                    <tr class="my_tr">
                        <th scope="row">{{$company->id}}</th>
                        <td>{{$company->name}}</td>
                        <td>{{$company->email}}</td>
                        <td>
                            @if($company->logo === "0")
                                <img src="https://cdn.shopify.com/s/files/1/1486/9104/t/28/assets/no-img.jpg?0" alt="">
                                @else
                                <img src="{{'storage/' . $company->logo}}" alt="">
                            @endif
                            </td>
                        <td>{{$company->website}}</td>
                        <td>
                            <form style="display: inline-block;" action="{{ route('company.destroy' , $company->id)}}" method="POST">
                                    <input name="_method" type="hidden" value="DELETE">
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-success del_modal"  data-toggle="modal" data-target="#myModal">X</button>
                            </form>
                            <a href="/company/{{$company->id}}/edit" class="btn btn-success"><i class="far fa-edit"></i></a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="text_center">
                            {{ $companies->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="profile-just" role="tabpanel" aria-labelledby="profile-tab-just">

        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script>
        $('.del_modal').on('click', function (e) {
            e.preventDefault();
            var form = $(this).parent();
            var form_action = form.attr('action');
            $('.delete_form').attr('action', form_action);
        })
    </script>
</body>
</html>

resources/views/crud/update.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Document</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .images_box {
            width: 100px;
            height: 100px;
            overflow: hidden;
            margin-right: 15px;
            position: relative;
        }

        .images_box img {
            width: 100%;
            height: 100%;

        }

        .images_block {
            margin-top: 50px;
            display: flex;
            flex-wrap: wrap;
            padding: 30px;
            border: 1px solid #000000;
        }


        .images_box a{
            padding: 5px;
            background-color: rgba(0,0,0,.4);
            position: absolute;
            right: 0;
            top: 0;
            color: #ffffff;
        }

        .modal-body form {
            display: inline-block;
        }
    </style>


</head>
<body>

<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
                <form action="">
                    @csrf
                    {{ method_field('POST') }}
                    <input type="hidden">
                    <button class="btn btn-success" id="delete_img">Delete</button>
                </form>

                <form action="" method="post">
                    @csrf
                    {{ method_field('POST') }}
                    <input type="hidden" name="logo">
                    <button class="btn btn-danger" id="add_img">Add Profile Photo</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
@if($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-2">
                <ul>
                    @foreach($errors->all() as $error)
                        <li style="color: red;">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="images_box prof_img">
                @if($company->logo === '0')
                    <img src="https://cdn.shopify.com/s/files/1/1486/9104/t/28/assets/no-img.jpg?0" alt="">
                    @else
                    <img src="../../storage/{{$company->logo}}" alt="">
                    @endif


            </div>
        </div>
        <div class="col-md-10">
            <form action="{{route('company.update',$company->id )}}" enctype="multipart/form-data" method="post">
                @csrf
                @method('POST')
                {{ method_field('PUT') }}
                <div class="form_group">
                    <input type="text" placeholder="Name" class="form-control" name="name" value="{{$company->name}}">
                    <input type="email" placeholder="Email" class="form-control" name="email" value="{{$company->email}}">
                    <input type="text" placeholder="Website" class="form-control" name="website" value="{{$company->website}}">
                    <input type="file" name="logo[]" multiple>
                    <button class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
    <div class="images_block">
        @if($CompanyImages)
            @php
                $ImgCount = count($CompanyImages);
            @endphp
            @for($i = 0; $i < $ImgCount; $i++)
                <div class="images_box" data-ImgID="{{$CompanyImages[$i]->id}}">
                    <a href="" class="img_val" data-ImgID="{{$CompanyImages[$i]->id}}"  data-toggle="modal" data-target="#myModal">
                        <i class="far fa-edit"></i>
                    </a>
                    <img src="../../storage/{{$CompanyImages[$i]->image_name}}" alt="">
                </div>
            @endfor
        @endif
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
    $('.img_val').on('click', function () {

        var val = $(this).data('imgid');
        $('.modal-body form input').val(val);

    })
</script>

<script>
    $(document).ready(function(e){
        $('#add_img').click(function(){
            $imgID = $('.modal-body form input').val();

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            jQuery.ajax({
                url: '/company/addProfile',
                type: 'post',
                data:{
                    'imgID':$imgID
                },
                success:function(data){
                    if (data){
                        $('.prof_img img').attr('src', '../../storage/'+ data )
                        $('body').removeClass("modal-open")
                        $('.modal-backdrop').removeClass('modal-backdrop');
                        $('#myModal').removeClass('show').css('display', 'none');
                    }
                    console.log(data);
                },
                error: function (xhr, b, c) {
                    console.log('error AddProfileImage');
                }
            });
            return false;
        });



        $('#delete_img').click(function(){

            $imgID = $('.modal-body form input').val();

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            jQuery.ajax({
                url: '/company/deleteImage',
                type: 'post',
                data:{
                    'imgID':$imgID
                },
                success:function(data){
                    if (data){
                        console.log(data);
                        $('.images_box').each(function () {
                            if( parseInt(data)  === $(this).data('imgid')){
                                $(this).remove();
                            }
                        })
                        $('body').removeClass("modal-open")
                        $('.modal-backdrop').removeClass('modal-backdrop');
                        $('#myModal').removeClass('show').css('display', 'none');
                    }
                },
                error: function () {
                    console.log('error DeleteImage');
                }
            });
            return false;
        });
    });
</script>

</body>
</html>